export { default as Testimonials } from './Testimonials/Testimonials'
export { default as Cta } from './Cta/Cta'
export { default as NewCourses } from './NewCourses/NewCourses'
export { default as TopCategories } from './TopCategories/TopCategories'
export { default as Stats } from './Stats/Stats'
export { default as ReasonsToStart } from './ReasonsToStart/ReasonsToStart'