import React, { ReactElement } from 'react'
import Head from 'next/head'
// Components
import { MainLayout } from '@/components/layouts'
import { Cta, NewCourses, ReasonsToStart, Stats } from '@/components/home'
import { reasonsToStart } from 'data/reasons-to-start'
import { stats } from './../data/stats'

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Cta />
      <NewCourses />
      <Stats stats={stats} />
      <ReasonsToStart articles={reasonsToStart} />
    </>
  )
}

Home.getLayout = function getLayout(page: ReactElement) {
  return <MainLayout>{page}</MainLayout>
}

export default Home
